### PR TITLE
NHUB-106 ADD: strftime replaced by datetime_short.

### PR DESCRIPTION
**Pull request by dev-tsoni**

### CODE REVIEW

**Review by MarkLark86 — CHANGES_REQUESTED** [review]
The following template is still using `strftime`:
- https://github.com/superdesk/newsroom-app-stt/blob/master/server/theme/company_expiry_email.txt

**Comment by dev-tsoni** [comment]
> The following template is still using `strftime`:
> 
> * https://github.com/superdesk/newsroom-app-stt/blob/master/server/theme/company_expiry_email.txt

The file is included in the PR.

**Comment by MarkLark86** [comment]
> > The following template is still using `strftime`:
> > 
> > * https://github.com/superdesk/newsroom-app-stt/blob/master/server/theme/company_expiry_email.txt
> 
> The file is included in the PR.

You have changed the `.html` template, there is also the `.txt` template that needs changing also

**Comment by dev-tsoni** [comment]
> > > The following template is still using `strftime`:
> > > 
> > > * https://github.com/superdesk/newsroom-app-stt/blob/master/server/theme/company_expiry_email.txt
> > 
> > 
> > The file is included in the PR.
> 
> You have changed the `.html` template, there is also the `.txt` template that needs changing also

Ohh, I see. I searched for strftime in html files.

**Review by MarkLark86 — APPROVED** [review]

**Pull request merged**
