### PR TITLE
[NHUB-16] Show more metadata in wire compact view

### PR DESCRIPTION
**Pull request by MarkLark86**
Depends on https://github.com/superdesk/newsroom-core/pull/12

### CODE REVIEW

**Comment by MarkLark86** [comment]
Marked as `draft` until https://github.com/superdesk/newsroom-core/pull/12 is merged

**Comment by MarkLark86** [comment]
@petrjasek This one is ready for review and using upstream superdesk/newsroom-core repo.
I am unable to assign a reviewer in this repo (could you have a look at the settings please?)

**Comment by petrjasek** [comment]
updated the config, can you do it now @MarkLark86 ?

**Review by petrjasek — APPROVED** [review]

**Comment by MarkLark86** [comment]
> updated the config, can you do it now @MarkLark86 ?

Yup, it's available now thanks

**Pull request merged**
